/* Resource File Indices for GNVAVIEW */

#define MAIN     0   /* Menu Tree */
#define MOPEN    7   /* STRING in tree MAIN */
#define MCLIP    9   /* STRING in tree MAIN */
#define MBLOCK   10  /* STRING in tree MAIN */
#define MPRINT   11  /* STRING in tree MAIN */
#define MFEED    12  /* STRING in tree MAIN */
#define MSAVE    14  /* STRING in tree MAIN */
#define MRELOAD  15  /* STRING in tree MAIN */
#define MQUIT    17  /* STRING in tree MAIN */
#define MHEX     19  /* STRING in tree MAIN */
#define MFONT    21  /* STRING in tree MAIN */
#define MSCROLL  22  /* STRING in tree MAIN */
#define MNAME    24  /* STRING in tree MAIN */
#define MHORIZ   25  /* STRING in tree MAIN */
#define MVERT    26  /* STRING in tree MAIN */
#define MABOUT   28  /* STRING in tree MAIN */
#define MHELP    29  /* STRING in tree MAIN */

#define FONTOPTS 1   /* Form/Dialog */
#define FOSAMP   3   /* BUTTON in tree FONTOPTS */
#define FOSAMP1  4   /* TEXT in tree FONTOPTS */
#define FOFONT   9   /* BUTTON in tree FONTOPTS */
#define FOPDWN   13  /* BOXCHAR in tree FONTOPTS */
#define FOPT     14  /* BUTTON in tree FONTOPTS */
#define FOPUP    15  /* BOXCHAR in tree FONTOPTS */
#define FOOK     16  /* BUTTON in tree FONTOPTS */
#define FOCANC   17  /* BUTTON in tree FONTOPTS */

#define SCRLOPTS 2   /* Form/Dialog */
#define SOCMI    4   /* BOXCHAR in tree SCRLOPTS */
#define SOCNUM   5   /* FBOXTEXT in tree SCRLOPTS */
#define SOCPL    6   /* BOXCHAR in tree SCRLOPTS */
#define SOLMI    8   /* BOXCHAR in tree SCRLOPTS */
#define SOLNUM   9   /* FBOXTEXT in tree SCRLOPTS */
#define SOLPL    10  /* BOXCHAR in tree SCRLOPTS */
#define SOMEM    12  /* BOXTEXT in tree SCRLOPTS */
#define SOALL    14  /* BUTTON in tree SCRLOPTS */
#define SOOK     15  /* BUTTON in tree SCRLOPTS */

#define MISCOPTS 3   /* Form/Dialog */
#define MOOK     3   /* BUTTON in tree MISCOPTS */

#define TOSICON  4   /* Form/Dialog */

#define ABOUT    5   /* Form/Dialog */
#define AMOVE    1   /* BUTTON in tree ABOUT */

#define NOWIND   0   /* Alert String */

#define ALNOMEM  1   /* Alert String */

#define ALCFGVER 2   /* Alert String */

#define ALCFGERR 3   /* Alert String */

#define ALEXISTS 4   /* Alert String */

#define ALDELETE 5   /* Alert String */

#define ALOPEN   6   /* Alert String */

#define BADCLIP  7   /* Alert String */

#define NOCREAT  8   /* Alert String */

#define NOWRITE  9   /* Alert String */

#define ALFULL   10  /* Alert String */

#define ALNOGEN  11  /* Alert String */

#define ALVDI    12  /* Alert String */

#define NOHELP   13  /* Alert String */

#define SYSTEM   14  /* Free String */

#define TERMTXT  15  /* Free String */

#define SAVEPATH 16  /* Free String */

#define OPENPATH 17  /* Free String */

#define ACCFILE  18  /* Free String */

#define ACCNAME  19  /* Free String */

#define MORE     20  /* Free String */

#define LOADING  21  /* Free String */

#define PAGING   22  /* Free String */

#define SEOF     23  /* Free String */
