/* Resource file indices for GNVA_MAC. */

#define MMENU            0   /* Menu-tree */
#define OPEN             9   /* STRING in tree MMENU */
#define NEW              10  /* STRING in tree MMENU */
#define SAVE             12  /* STRING in tree MMENU */
#define SAVEAS           13  /* STRING in tree MMENU */
#define QUIT             15  /* STRING in tree MMENU */
#define EDMAC            17  /* STRING in tree MMENU */
#define EDNEW            18  /* STRING in tree MMENU */
#define MGLOBL           19  /* STRING in tree MMENU */
#define MCUT             21  /* STRING in tree MMENU */
#define MCOPY            22  /* STRING in tree MMENU */
#define MPASTE           23  /* STRING in tree MMENU */
#define MDEL             24  /* STRING in tree MMENU */
#define NEWMAC           26  /* STRING in tree MMENU */
#define MTIMER           28  /* STRING in tree MMENU */
#define MBUTTON          29  /* STRING in tree MMENU */
#define MMOUSE           30  /* STRING in tree MMENU */
#define MKEYBD           31  /* STRING in tree MMENU */
#define MISC             33  /* STRING in tree MMENU */
#define MDFLT            34  /* STRING in tree MMENU */
#define SSAVE            35  /* STRING in tree MMENU */
#define MABOUT           37  /* STRING in tree MMENU */
#define MHELP            38  /* STRING in tree MMENU */

#define EMENU            1   /* Menu-tree */
#define ECUT             8   /* STRING in tree EMENU */
#define ECOPY            9   /* STRING in tree EMENU */
#define EPASTE           10  /* STRING in tree EMENU */
#define EDEL             11  /* STRING in tree EMENU */
#define ECLOSE           13  /* STRING in tree EMENU */
#define EMTIMER          15  /* STRING in tree EMENU */
#define EMBUTN           16  /* STRING in tree EMENU */
#define EMMOUSE          17  /* STRING in tree EMENU */
#define EMKEYBD          18  /* STRING in tree EMENU */
#define EMSOUND          19  /* STRING in tree EMENU */
#define EMDATE           20  /* STRING in tree EMENU */
#define EMTIME           21  /* STRING in tree EMENU */
#define EMMSG            22  /* STRING in tree EMENU */
#define ERECORD          24  /* STRING in tree EMENU */
#define ETEST            25  /* STRING in tree EMENU */
#define EALLTIM          27  /* STRING in tree EMENU */
#define ERTIMER          29  /* STRING in tree EMENU */
#define ERBUTN           30  /* STRING in tree EMENU */
#define ERMOUSE          31  /* STRING in tree EMENU */
#define ERKEYBD          32  /* STRING in tree EMENU */
#define EOTIMER          34  /* STRING in tree EMENU */
#define EOBUTN           35  /* STRING in tree EMENU */
#define EOMOUSE          36  /* STRING in tree EMENU */
#define EOKEYBD          37  /* STRING in tree EMENU */
#define EOALL            38  /* STRING in tree EMENU */
#define EHELP            40  /* STRING in tree EMENU */

#define MISCOPTS         2   /* Form/Dialog-box */
#define MOKEY            3   /* BUTTON in tree MISCOPTS */
#define MOSIZE           4   /* FTEXT in tree MISCOPTS */
#define MOGMAT           5   /* BOXTEXT in tree MISCOPTS */
#define MOGMA            6   /* BOXTEXT in tree MISCOPTS */
#define MOAUTO           7   /* BUTTON in tree MISCOPTS */
#define MOHELP           8   /* BUTTON in tree MISCOPTS */
#define MOOK             9   /* BUTTON in tree MISCOPTS */

#define EVENTS           3   /* Form/Dialog-box */
#define EMAC             1   /* BOX in tree EVENTS */
#define EVMACNAM         2   /* FTEXT in tree EVENTS */
#define EVMACKEY         3   /* BUTTON in tree EVENTS */
#define EVAON            4   /* BUTTON in tree EVENTS */
#define EVAS1            5   /* STRING in tree EVENTS */
#define EVAPOP           6   /* BUTTON in tree EVENTS */
#define EVAFROM          7   /* FTEXT in tree EVENTS */
#define EVADATE          8   /* FTEXT in tree EVENTS */
#define ETIMER           9   /* BOX in tree EVENTS */
#define EVTIMER          11  /* FTEXT in tree EVENTS */
#define EBUTTON          12  /* BOX in tree EVENTS */
#define EVRIGHT          14  /* BUTTON in tree EVENTS */
#define EVLEFT           15  /* BUTTON in tree EVENTS */
#define EMOUSE           16  /* BOX in tree EVENTS */
#define EVMX             18  /* FTEXT in tree EVENTS */
#define EVMY             19  /* FTEXT in tree EVENTS */
#define EVMREAD          20  /* BUTTON in tree EVENTS */
#define EKEYBD           21  /* BOX in tree EVENTS */
#define EVKKEY           23  /* BUTTON in tree EVENTS */
#define ESOUND           24  /* BOX in tree EVENTS */
#define EVBELL           26  /* BUTTON in tree EVENTS */
#define EVUP             27  /* BUTTON in tree EVENTS */
#define EVDOWN           28  /* BUTTON in tree EVENTS */
#define EDATE            29  /* BOX in tree EVENTS */
#define EVDPOP           31  /* BUTTON in tree EVENTS */
#define ETIME            32  /* BOX in tree EVENTS */
#define EVTPOP           34  /* BUTTON in tree EVENTS */
#define EMSG             35  /* BOX in tree EVENTS */
#define EVMSAM           37  /* STRING in tree EVENTS */
#define EVMEDIT          38  /* BUTTON in tree EVENTS */

#define MACICON          4   /* Form/Dialog-box */

#define MESSAGE          5   /* Form/Dialog-box */
#define MSGSEG           2   /* STRING in tree MESSAGE */
#define MSGCOUNT         5   /* BOXTEXT in tree MESSAGE */

#define ABOUT            6   /* Form/Dialog-box */
#define ABDEMO           6   /* STRING in tree ABOUT */

#define DEFAULTS         7   /* Form/Dialog-box */
#define DFBELL           5   /* BUTTON in tree DEFAULTS */
#define DFDD0            8   /* BUTTON in tree DEFAULTS */
#define DFDATE0          16  /* FTEXT in tree DEFAULTS */
#define DFDTEST          24  /* BUTTON in tree DEFAULTS */
#define DFDT0            27  /* BUTTON in tree DEFAULTS */
#define DFTIME0          35  /* FTEXT in tree DEFAULTS */
#define DFTTEST          43  /* BUTTON in tree DEFAULTS */
#define DFOK             45  /* BUTTON in tree DEFAULTS */

#define EDITICON         8   /* Form/Dialog-box */

#define ALLTIM           9   /* Form/Dialog-box */
#define ALLEDIT          2   /* FTEXT in tree ALLTIM */
#define ALLOK            4   /* BUTTON in tree ALLTIM */

#define DATEPOP          10  /* Form/Dialog-box */

#define TIMEPOP          11  /* Form/Dialog-box */

#define AUTOPOP          12  /* Form/Dialog-box */

#define NEWMSG           13  /* Form/Dialog-box */
#define NM1              2   /* FTEXT in tree NEWMSG */
#define NMOK             7   /* BUTTON in tree NEWMSG */
#define NMCANC           8   /* BUTTON in tree NEWMSG */
#define NMCLOSE          9   /* BUTTON in tree NEWMSG */

#define ALNOVDI          0   /* Alert-string */

#define NOHELP           1   /* Alert-string */

#define ALNOGEN          2   /* Alert-string */

#define NOWIND           3   /* Alert-string */

#define TITLE            4   /* Free String */

#define FSTITLE          5   /* Free String */

#define FSSAVAS          6   /* Free String */

#define MACDIR           7   /* Free String */

#define HELPMAIN         8   /* Free String */

#define GETKEY           9   /* Free String */

#define MSGSTR           10  /* Free String */

#define MINFO            11  /* Free String */

#define MSELECT          12  /* Free String */

#define EINFO            13  /* Free String */

#define EVEDIT           14  /* Free String */

#define HELPEDIT         15  /* Free String */

#define GETXY            16  /* Free String */

#define MONTHS           17  /* Free String */

#define SMONTHS          18  /* Free String */

#define BADOPEN          19  /* Alert-string */

#define BADLOAD          20  /* Alert-string */

#define NOMEMORY         21  /* Alert-string */

#define SAVEOVER         22  /* Alert-string */

#define BADSAVE          23  /* Alert-string */

#define BADCLIP          24  /* Alert-string */

#define MACLONG          25  /* Alert-string */

#define OBJBIG           26  /* Alert-string */

#define NEEDSAVE         27  /* Alert-string */

#define BADDATE          28  /* Alert-string */

#define BADTIME          29  /* Alert-string */

#define NOTGLOB          30  /* Alert-string */
