/* Resource File Indices for GNVAHELP */

#define HMENU    0   /* Menu Tree */
#define MHELP    8   /* STRING in tree HMENU */
#define MHPATH   9   /* STRING in tree HMENU */
#define MCLIP    11  /* STRING in tree HMENU */
#define MTEXT    12  /* STRING in tree HMENU */
#define MBLOCK   13  /* STRING in tree HMENU */
#define MQUIT    15  /* STRING in tree HMENU */
#define MFIND    17  /* STRING in tree HMENU */
#define MINDEX   18  /* STRING in tree HMENU */
#define MPREV    19  /* STRING in tree HMENU */
#define MUSING   21  /* STRING in tree HMENU */
#define MFONT    23  /* STRING in tree HMENU */
#define MSAVE    25  /* STRING in tree HMENU */
#define MLOAD    26  /* STRING in tree HMENU */

#define FIND     1   /* Form/Dialog */
#define FTOPIC   3   /* FTEXT in tree FIND */
#define FMATCH   5   /* BUTTON in tree FIND */
#define FALL     6   /* BUTTON in tree FIND */
#define FOK      7   /* BUTTON in tree FIND */

#define HICON    2   /* Form/Dialog */

#define WINDOPTS 3   /* Form/Dialog */
#define FOSAMP   3   /* BUTTON in tree WINDOPTS */
#define FOSAMP1  4   /* TEXT in tree WINDOPTS */
#define FOFONT   9   /* BUTTON in tree WINDOPTS */
#define FOPDWN   13  /* BOXCHAR in tree WINDOPTS */
#define FOPT     14  /* BUTTON in tree WINDOPTS */
#define FOPUP    15  /* BOXCHAR in tree WINDOPTS */
#define FOOK     16  /* BUTTON in tree WINDOPTS */
#define FOCANC   17  /* BUTTON in tree WINDOPTS */

#define ALNOGEN  0   /* Alert String */

#define READERR  1   /* Alert String */

#define ALNOMEM  2   /* Alert String */

#define ALNOTOP  3   /* Alert String */

#define ALMEMHLP 4   /* Alert String */

#define ALNOTHLP 5   /* Alert String */

#define ALOPEN   6   /* Alert String */

#define ALWIND   7   /* Alert String */

#define ALCFGVER 8   /* Alert String */

#define ALCFGERR 9   /* Alert String */

#define ALVDI    10  /* Alert String */

#define NOCREAT  11  /* Alert String */

#define NOWRITE  12  /* Alert String */

#define BADCLIP  13  /* Alert String */

#define TITLE    14  /* Free String */

#define EMPLINE  15  /* Free String */

#define EMPLINE2 16  /* Free String */

#define EMPLINE3 17  /* Free String */

#define EMPLINE4 18  /* Free String */

#define EMPLINE5 19  /* Free String */

#define INDEX    20  /* Free String */

#define HELPTITL 21  /* Free String */

#define SYSTEM   22  /* Free String */

#define HELPSTR  23  /* Free String */

#define HELPPATH 24  /* Free String */

#define SAVEPATH 25  /* Free String */
