\index
\hidden Index
\casesens Geneva Desk
Geneva Desktop Pattern
----------------------

  When you are not running any applications that have their own desktops,
  Geneva normally uses a default gray or green pattern for the desktop. it
  also uses this same desktop when switching to a singletasking
  application.

  Since there is normally no easy way to redefine the appearance of this
  "default desktop", the Geneva Desktop Pattern accessory was created. It
  allows you to customize the default desktop by choosing among the default
  fill patterns that are part of GEM. Furthermore, if you have NeoDesk 4,
  you can use NeoDesk's desktop pattern or picture.

  Please choose a topic from the list below:
    \#Installation\#
    \#Main Window\#
    \#Main Window Options\#
    \#Using With NeoDesk\#
    \#Cautions\#
\end

\casesens Installation
Installation
------------

  The Geneva Desktop Pattern application must be installed as a desk
  accessory. Copy GNVADESK.ACC and GNVADESK.RSC to the same folder you
  normally load your desk accessories from and reboot the computer.

  You can also copy the GNVADESK.HLP file to the GENEVA\\HELP directory,
  where Geneva's own help files should also be stored. You can leave the
  HLP file in the same directory as GNVADESK.ACC, but this may just add to
  the clutter in that directory.

Related Topics:  \#Index\#
\end

\casesens Main Window
The Main Window
---------------

The main window contains these elements:

\x3 Close box:      Clicking here will close the main window. Any changes you
                  have made to the options will be remembered, so that you
                  can reopen the window with the settings intact. However,
                  changes to the options do not actually go into effect.
                  To have them take place, you must use either the \#Set\#
                  button or the \#Ok\# button.

\x3 Mover bar:      This allows you to move the main window.

\x3 Iconify gadget: The iconify (\x7f) gadget will shrink the main window down
                  to a small window toward the lower left of the screen.
                  Double-clicking on the icon in the iconified window will
                  cause the window to reopen.

\x3 Menu bar:       Clicking on a title in the menu bar will allow you to
                  choose items in the menu. See the \#Main Window Options\#
                  section for descriptions of each menu entry.

Related Topics:  \#Index\#  \#Main Window Options\#
\end

\casesens Main Window Options
\hidden Use NeoDesk's Picture
\hidden Use NeoDesk's Pattern
\hidden Set
\hidden Ok
Main Window Options
-------------------

  The working area of the window contains a dialog which gives you control
  over the replacement desktop pattern:

  \x3 Sample:       In the upper left corner, there is a sample of what the
                  new desktop pattern will look like.

  \x3 Pattern:      Selecting the left or right arrows in the Pattern section
                  will cycle forward or backward through the list of
                  patterns. The center of this bar contains a sample of the
                  currently selected pattern. Clicking here will produce a
                  popup menu, from which you can choose a new pattern.

  \x3 Color:        Selecting the left or right arrows in the Color section
                  will cycle forward or backward through the list of 16
                  colors. The center of this bar contains a sample of the
                  current color. Clicking here will produce a popup menu,
                  from which you can choose a new color. Note that any
                  colors your current video display mode cannot reproduce
                  will be black.

  \x3 Use NeoDesk's Picture:  If you are using NeoDesk 4, then the desktop
                  pattern can be replaced with the picture, if any, that
                  NeoDesk is using as its desktop. Any Desktop Notes will
                  also be displayed. If NeoDesk is not using a desktop
                  picture, and the "Use NeoDesk's Pattern" option is not
                  selected, then things will look just like they would if
                  NeoDesk was not running: the normal pattern will be used.
                  \#Cautions\#

  \x3 Use NeoDesk's Pattern:  If you are using NeoDesk 4, then the desktop
                  pattern can be made the same as the one NeoDesk is using.
                  Any Desktop Notes will also be displayed.  However, if
                  NeoDesk is using a desktop picture, and the "Use
                  NeoDesk's Picture" option is selected, then the picture
                  will be used instead of the pattern. \#Cautions\#

  \x3 Set:          Selecting this button will update the default desktop
                  with the settings that are currently in the main dialog.
                  The window is left open so that you can make further
                  changes.

  \x3 Ok:           This button updates the default desktop with the settings
                  that are currently in the main dialog and closes the
                  window.

  \x3 Cancel:       This button will close the window. The options will also
                  revert to what they were when the Set or Ok button was
                  last used.

Related Topics:  \#Index\#  \#Main Window\#
\end

\casesens Cautions
\casesens Using With NeoDesk
Using with NeoDesk
------------------

  If you are using the \#Use NeoDesk's Picture\# or the \#Use NeoDesk's Pattern\#
  option, and NeoDesk quits or is Unloaded for Execution of another
  program, the default desktop will revert to the standard pattern. When
  and if NeoDesk returns, the pattern will be restored to the correct state
  automatically.

Related Topics:  \#Index\#
\end
