/* Resource File Indices for GNVADESK */

#define MMENU    0   /* Menu Tree */
#define MSAVE    7   /* STRING in tree MMENU */
#define MQUIT    8   /* STRING in tree MMENU */
#define MABOUT   10  /* STRING in tree MMENU */
#define MHELP    11  /* STRING in tree MMENU */

#define MDIAL    1   /* Form/Dialog */
#define MSAMP    1   /* IBOX in tree MDIAL */
#define MPLEFT   3   /* BOXCHAR in tree MDIAL */
#define MPAT     4   /* BOX in tree MDIAL */
#define MPRT     5   /* BOXCHAR in tree MDIAL */
#define MCLEFT   7   /* BOXCHAR in tree MDIAL */
#define MCOL     8   /* BOX in tree MDIAL */
#define MCRT     9   /* BOXCHAR in tree MDIAL */
#define MNPIC    10  /* BUTTON in tree MDIAL */
#define MNPAT    11  /* BUTTON in tree MDIAL */
#define MSET     12  /* BUTTON in tree MDIAL */
#define MOK      13  /* BUTTON in tree MDIAL */
#define MCANC    14  /* BUTTON in tree MDIAL */

#define PCOLORS  2   /* Form/Dialog */
#define PCOL0    1   /* BOXCHAR in tree PCOLORS */

#define PFILLS   3   /* Form/Dialog */

#define MICON    4   /* Form/Dialog */

#define ABOUT    5   /* Form/Dialog */
#define AMOVE    1   /* BUTTON in tree ABOUT */

#define ALNOVDI  0   /* Alert String */

#define NOHELP   1   /* Alert String */

#define ALNOGEN  2   /* Alert String */

#define NOWIND   3   /* Alert String */

#define NOTAPP   4   /* Alert String */

#define TITLE    5   /* Free String */

#define HELPMAIN 6   /* Free String */
