/* Resource File Indices for GNVA_TOS */

#define MAIN     0   /* Menu Tree */
#define MABOUT   8   /* STRING in tree MAIN */
#define MOPEN    10  /* STRING in tree MAIN */
#define MOUTPUT  11  /* STRING in tree MAIN */
#define MINPUT   12  /* STRING in tree MAIN */
#define MCLIP    14  /* STRING in tree MAIN */
#define MTEXT    15  /* STRING in tree MAIN */
#define MBLOCK   16  /* STRING in tree MAIN */
#define MSAVE    18  /* STRING in tree MAIN */
#define MRELOAD  19  /* STRING in tree MAIN */
#define MQUIT    21  /* STRING in tree MAIN */
#define MFONT    23  /* STRING in tree MAIN */
#define MSCROLL  24  /* STRING in tree MAIN */
#define MNAME    26  /* STRING in tree MAIN */
#define MHORIZ   27  /* STRING in tree MAIN */
#define MVERT    28  /* STRING in tree MAIN */
#define MMISC    30  /* STRING in tree MAIN */
#define MHELP    32  /* STRING in tree MAIN */

#define FONTOPTS 1   /* Form/Dialog */
#define FOSAMP   3   /* BUTTON in tree FONTOPTS */
#define FOSAMP1  4   /* TEXT in tree FONTOPTS */
#define FOFONT   9   /* BUTTON in tree FONTOPTS */
#define FOPDWN   13  /* BOXCHAR in tree FONTOPTS */
#define FOPT     14  /* BUTTON in tree FONTOPTS */
#define FOPUP    15  /* BOXCHAR in tree FONTOPTS */
#define FOOK     16  /* BUTTON in tree FONTOPTS */
#define FOCANC   17  /* BUTTON in tree FONTOPTS */

#define SCRLOPTS 2   /* Form/Dialog */
#define SOCMI    4   /* BOXCHAR in tree SCRLOPTS */
#define SOCNUM   5   /* FBOXTEXT in tree SCRLOPTS */
#define SOCPL    6   /* BOXCHAR in tree SCRLOPTS */
#define SOLMI    8   /* BOXCHAR in tree SCRLOPTS */
#define SOLNUM   9   /* FBOXTEXT in tree SCRLOPTS */
#define SOLPL    10  /* BOXCHAR in tree SCRLOPTS */
#define SOMEM    12  /* BOXTEXT in tree SCRLOPTS */
#define SOOK     13  /* BUTTON in tree SCRLOPTS */

#define MISCOPTS 3   /* Form/Dialog */
#define MOKEYS   3   /* BUTTON in tree MISCOPTS */
#define MOLINEA  4   /* BUTTON in tree MISCOPTS */
#define MOTERM   5   /* BUTTON in tree MISCOPTS */
#define MOARGV   6   /* BUTTON in tree MISCOPTS */
#define MOPAUSE  7   /* BUTTON in tree MISCOPTS */
#define MOOK     8   /* BUTTON in tree MISCOPTS */

#define PARAMS   4   /* Form/Dialog */
#define PARM1    3   /* FTEXT in tree PARAMS */
#define PARMOK   8   /* BUTTON in tree PARAMS */

#define TOSICON  5   /* Form/Dialog */

#define BADREDIR 0   /* Alert String */

#define NOWIND   1   /* Alert String */

#define ALNOMEM  2   /* Alert String */

#define ALCFGVER 3   /* Alert String */

#define ALCFGERR 4   /* Alert String */

#define ALABOUT  5   /* Alert String */

#define ALEXISTS 6   /* Alert String */

#define ALDELETE 7   /* Alert String */

#define ALOPEN   8   /* Alert String */

#define BADCLIP  9   /* Alert String */

#define NOCREAT  10  /* Alert String */

#define NOWRITE  11  /* Alert String */

#define ALFULL   12  /* Alert String */

#define ALNOGEN  13  /* Alert String */

#define ALVDI    14  /* Alert String */

#define ALTERMTOS 15  /* Alert String */

#define ALPRGOPEN 16  /* Alert String */

#define NOHELP   17  /* Alert String */

#define ALPRGOP2 18  /* Alert String */

#define SYSTEM   19  /* Free String */

#define TERMTXT  20  /* Free String */

#define SAVEPATH 21  /* Free String */

#define OPENPATH 22  /* Free String */

#define OUTPATH  23  /* Free String */

#define INPATH   24  /* Free String */

#define RETURN   25  /* Free String */
