/* Resource file indices for TEST. */

#define TREE1            0   /* Menu-tree */
#define TINFO            9   /* STRING in tree TREE1 */
#define SPRINT           18  /* STRING in tree TREE1 */
#define BLIT             19  /* STRING in tree TREE1 */
#define SET              20  /* STRING in tree TREE1 */
#define FORMS            21  /* STRING in tree TREE1 */
#define POP              22  /* STRING in tree TREE1 */
#define UPDATE           24  /* STRING in tree TREE1 */
#define QUIT             26  /* STRING in tree TREE1 */
#define POPSTART         29  /* STRING in tree TREE1 */

#define FORM1            1   /* Form/Dialog-box */

#define TREE2            2   /* Form/Dialog-box */

#define WINMENU          3   /* Menu-tree */

#define TREE6            4   /* Form/Dialog-box */

#define POPUPS           5   /* Form/Dialog-box */
#define POP1             1   /* BOX in tree POPUPS */
#define SUB3             4   /* STRING in tree POPUPS */
#define MPOP             6   /* STRING in tree POPUPS */
#define POP2             7   /* BOX in tree POPUPS */

#define FORM7            6   /* Form/Dialog-box */

#define FORM8            7   /* Form/Dialog-box */
