/* Resource file indices for TASKMAN. */

#define TMENU            0   /* Menu-tree */
#define OPEN             8   /* STRING in tree TMENU */
#define TMPFLAGS         10  /* STRING in tree TMENU */
#define PERFLAGS         11  /* STRING in tree TMENU */
#define SLEEP            13  /* STRING in tree TMENU */
#define TERM             14  /* STRING in tree TMENU */
#define QUIT             16  /* STRING in tree TMENU */
#define KEYBOARD         18  /* STRING in tree TMENU */
#define TWINDOWS         19  /* STRING in tree TMENU */
#define WCOLORS          20  /* STRING in tree TMENU */
#define DIALOGS          21  /* STRING in tree TMENU */
#define MISC             23  /* STRING in tree TMENU */
#define VIDEO            24  /* STRING in tree TMENU */
#define SAVE             29  /* STRING in tree TMENU */
#define RELOAD           30  /* STRING in tree TMENU */
#define TMSAVE           32  /* STRING in tree TMENU */

#define MISCOPTS         1   /* Form/Dialog-box */
#define MOPULL           2   /* BUTTON in tree MISCOPTS */
#define MOTOPALL         3   /* BUTTON in tree MISCOPTS */
#define MOTOP            4   /* BUTTON in tree MISCOPTS */
#define MOINS            5   /* BUTTON in tree MISCOPTS */
#define MOLONG           6   /* BUTTON in tree MISCOPTS */
#define MOFOLL           7   /* BUTTON in tree MISCOPTS */
#define MOCOL            8   /* BUTTON in tree MISCOPTS */
#define MOGROW           9   /* BUTTON in tree MISCOPTS */
#define MOUPDATE         10  /* BUTTON in tree MISCOPTS */
#define MOALERT          11  /* BUTTON in tree MISCOPTS */
#define MOVIDEO          12  /* BUTTON in tree MISCOPTS */
#define MOMOUSE          13  /* BUTTON in tree MISCOPTS */
#define MOCOLOR          14  /* BUTTON in tree MISCOPTS */
#define MONWIND          16  /* BUTTON in tree MISCOPTS */
#define MOWIND           17  /* BUTTON in tree MISCOPTS */
#define MOGAD            18  /* FTEXT in tree MISCOPTS */
#define MOHELP           19  /* BUTTON in tree MISCOPTS */
#define MOOK             20  /* BUTTON in tree MISCOPTS */

#define KEYOPTS          2   /* Form/Dialog-box */
#define KOBACK           2   /* BOX in tree KEYOPTS */
#define KOPRESS          3   /* BUTTON in tree KEYOPTS */
#define KOCLICK          4   /* BUTTON in tree KEYOPTS */
#define KOOTHER          6   /* BUTTON in tree KEYOPTS */
#define KOONEXT          7   /* BOXCHAR in tree KEYOPTS */
#define KOBOX            8   /* BUTTON in tree KEYOPTS */
#define KOKEY            10  /* STRING in tree KEYOPTS */
#define KOCNTRL          11  /* BUTTON in tree KEYOPTS */
#define KOREAD           12  /* BUTTON in tree KEYOPTS */
#define KOSHIFT          13  /* BUTTON in tree KEYOPTS */
#define KOALT            14  /* BUTTON in tree KEYOPTS */
#define KOCLEAR          15  /* BUTTON in tree KEYOPTS */
#define KOHELP           16  /* BUTTON in tree KEYOPTS */
#define KOQUIT           17  /* BUTTON in tree KEYOPTS */

#define DIALOPTS         3   /* Form/Dialog-box */
#define DOOUT            3   /* BUTTON in tree DIALOPTS */
#define DO3DBUT          4   /* BUTTON in tree DIALOPTS */
#define DOEXIT           5   /* BUTTON in tree DIALOPTS */
#define DOOTHER          6   /* BUTTON in tree DIALOPTS */
#define DOSBOX           8   /* BOX in tree DIALOPTS */
#define DOSBOXT          9   /* TEXT in tree DIALOPTS */
#define DOS3D            10  /* BOXTEXT in tree DIALOPTS */
#define DOSEXIT          11  /* BOXTEXT in tree DIALOPTS */
#define DOSOTHER         12  /* BOXTEXT in tree DIALOPTS */
#define DOBBOX           13  /* BUTTON in tree DIALOPTS */
#define DROUND           14  /* BUTTON in tree DIALOPTS */
#define DGNVA3D          15  /* BUTTON in tree DIALOPTS */
#define DSHADOW          16  /* BUTTON in tree DIALOPTS */
#define DOUTLINE         17  /* BUTTON in tree DIALOPTS */
#define DATARI3D         18  /* BUTTON in tree DIALOPTS */
#define DOBLEFT          19  /* BOXCHAR in tree DIALOPTS */
#define DOTBOX           22  /* BUTTON in tree DIALOPTS */
#define DTSHAD           23  /* BUTTON in tree DIALOPTS */
#define DTBOLD           24  /* BUTTON in tree DIALOPTS */
#define DOPAQUE          25  /* BUTTON in tree DIALOPTS */
#define DTBOX            26  /* BOX in tree DIALOPTS */
#define DOTLEFT          29  /* BOXCHAR in tree DIALOPTS */
#define DOFBOX           32  /* BUTTON in tree DIALOPTS */
#define DOFLEFT          35  /* BOXCHAR in tree DIALOPTS */
#define DOPLEFT          39  /* BOXCHAR in tree DIALOPTS */
#define DOHELP           42  /* BUTTON in tree DIALOPTS */
#define DOOK             43  /* BUTTON in tree DIALOPTS */

#define WINDOPTS         4   /* Form/Dialog-box */
#define XWOUTER          2   /* BOX in tree WINDOPTS */
#define XWMOVE           3   /* BOXTEXT in tree WINDOPTS */
#define XWBACK           4   /* BOXTEXT in tree WINDOPTS */
#define XWFULL           5   /* BOXTEXT in tree WINDOPTS */
#define XWINFO           6   /* BOXTEXT in tree WINDOPTS */
#define XWUP             7   /* BOXTEXT in tree WINDOPTS */
#define XWVBIGSL         8   /* BOX in tree WINDOPTS */
#define XWVSMLSL         9   /* BOX in tree WINDOPTS */
#define WOWDWN           12  /* BOXCHAR in tree WINDOPTS */
#define WOWID            13  /* BUTTON in tree WINDOPTS */
#define WOWUP            14  /* BOXCHAR in tree WINDOPTS */
#define WOHDWN           16  /* BOXCHAR in tree WINDOPTS */
#define WOHT             17  /* BUTTON in tree WINDOPTS */
#define WOHUP            18  /* BOXCHAR in tree WINDOPTS */
#define WOFONT           20  /* BUTTON in tree WINDOPTS */
#define WOPDWN           22  /* BOXCHAR in tree WINDOPTS */
#define WOPT             23  /* BUTTON in tree WINDOPTS */
#define WOPUP            24  /* BOXCHAR in tree WINDOPTS */
#define WOSLEFT          28  /* BOXCHAR in tree WINDOPTS */
#define WOSPOP           29  /* BOX in tree WINDOPTS */
#define WOSSAMP          30  /* IBOX in tree WINDOPTS */
#define WOSRT            31  /* BOXCHAR in tree WINDOPTS */
#define WOHELP           32  /* BUTTON in tree WINDOPTS */
#define WODFLT           33  /* BUTTON in tree WINDOPTS */
#define WOOK             34  /* BUTTON in tree WINDOPTS */

#define FLAGOPTS         5   /* Form/Dialog-box */
#define FONAME           2   /* FTEXT in tree FLAGOPTS */
#define FOSEL            3   /* BUTTON in tree FLAGOPTS */
#define FOPREV           4   /* BUTTON in tree FLAGOPTS */
#define FODESC           5   /* FTEXT in tree FLAGOPTS */
#define FONEXT           6   /* BUTTON in tree FLAGOPTS */
#define FOMULTI          7   /* BUTTON in tree FLAGOPTS */
#define FOFIND           8   /* BUTTON in tree FLAGOPTS */
#define FOHAND           9   /* BUTTON in tree FLAGOPTS */
#define FOLIMIT          10  /* BUTTON in tree FLAGOPTS */
#define FOLNUM           11  /* FTEXT in tree FLAGOPTS */
#define FOCLEAR          12  /* BUTTON in tree FLAGOPTS */
#define FOLEFT           13  /* BUTTON in tree FLAGOPTS */
#define FOWMAX           14  /* BUTTON in tree FLAGOPTS */
#define FOMAXRED         15  /* BUTTON in tree FLAGOPTS */
#define FOREDRAW         16  /* BUTTON in tree FLAGOPTS */
#define FOSPEC           17  /* BUTTON in tree FLAGOPTS */
#define FOROUND          18  /* BUTTON in tree FLAGOPTS */
#define FOAUTO           19  /* BUTTON in tree FLAGOPTS */
#define FOUNDRAW         20  /* BUTTON in tree FLAGOPTS */
#define FOKEEP           21  /* BUTTON in tree FLAGOPTS */
#define FOAES40          22  /* BUTTON in tree FLAGOPTS */
#define FOHELP           23  /* BUTTON in tree FLAGOPTS */
#define FONEW            24  /* BUTTON in tree FLAGOPTS */
#define FODEL            25  /* BUTTON in tree FLAGOPTS */
#define FOKEYS           26  /* BUTTON in tree FLAGOPTS */
#define FOOK             27  /* BUTTON in tree FLAGOPTS */

#define VIDOPTS          6   /* Form/Dialog-box */
#define VOSTLOW          2   /* BUTTON in tree VIDOPTS */
#define VOOK             8   /* BUTTON in tree VIDOPTS */
#define VOHELP           10  /* BUTTON in tree VIDOPTS */

#define FLKEYS           7   /* Form/Dialog-box */
#define FLOPEN           6   /* BUTTON in tree FLKEYS */
#define FLRES1           7   /* BUTTON in tree FLKEYS */
#define FLRES2           8   /* BUTTON in tree FLKEYS */
#define FLRES3           9   /* BUTTON in tree FLKEYS */
#define FKHELP           18  /* BUTTON in tree FLKEYS */

#define PCOLORS          8   /* Form/Dialog-box */
#define PCOL0            1   /* BOXCHAR in tree PCOLORS */

#define PFILLS           9   /* Form/Dialog-box */
#define PFIL0            1   /* BOXCHAR in tree PFILLS */

#define FALCVID          10  /* Form/Dialog-box */
#define FALTC40          3   /* BUTTON in tree FALCVID */
#define FALTC80          4   /* BUTTON in tree FALCVID */
#define FALC2            6   /* BUTTON in tree FALCVID */
#define FALSTL           12  /* BUTTON in tree FALCVID */
#define FALSTM           13  /* BUTTON in tree FALCVID */
#define FALSTH           14  /* BUTTON in tree FALCVID */
#define FALDBL           15  /* BUTTON in tree FALCVID */
#define FALHELP          16  /* BUTTON in tree FALCVID */
#define FALOK            17  /* BUTTON in tree FALCVID */

#define FLFIND           11  /* Form/Dialog-box */
#define FLFNAME          2   /* FTEXT in tree FLFIND */
#define FLFOK            3   /* BUTTON in tree FLFIND */

#define TASKICON         12  /* Form/Dialog-box */

#define WINDGADS         13  /* Form/Dialog-box */
#define WGDFBOX          2   /* BOX in tree WINDGADS */
#define WGDPLEFT         5   /* BOXCHAR in tree WINDGADS */
#define WGDCLEFT         9   /* BOXCHAR in tree WINDGADS */
#define WGDBBOX          12  /* BOX in tree WINDGADS */
#define WGD3D            14  /* BUTTON in tree WINDGADS */
#define WGDBLEFT         15  /* BOXCHAR in tree WINDGADS */
#define WGDTBOX          18  /* BOX in tree WINDGADS */
#define WGDTINV          19  /* IBOX in tree WINDGADS */
#define WGDSHAD          21  /* BUTTON in tree WINDGADS */
#define WGDOPAQ          22  /* BUTTON in tree WINDGADS */
#define WGDTLEFT         24  /* BOXCHAR in tree WINDGADS */
#define WGDXBOX          27  /* BOX in tree WINDGADS */
#define WGDTOP           28  /* BUTTON in tree WINDGADS */
#define WGDHELP          29  /* BUTTON in tree WINDGADS */
#define WGDCANC          30  /* BUTTON in tree WINDGADS */
#define WGDOK            31  /* BUTTON in tree WINDGADS */

#define PSEPS            14  /* Form/Dialog-box */
#define PSEP0            17  /* IBOX in tree PSEPS */

#define POTHKEYS         15  /* Form/Dialog-box */
#define KOGAD            1   /* STRING in tree POTHKEYS */
#define KOPROCESS        7   /* STRING in tree POTHKEYS */

#define ALNONAME         0   /* Alert-string */

#define ALNOVDI          1   /* Alert-string */

#define ALSAVE           2   /* Alert-string */

#define ALNOSHUT         3   /* Alert-string */

#define ALREZ            4   /* Alert-string */

#define ALTERM           5   /* Alert-string */

#define ALOPEN           6   /* Alert-string */

#define NOHELP           7   /* Alert-string */

#define ALNOGEN          8   /* Alert-string */

#define NOWIND           9   /* Alert-string */

#define TITLE            10  /* Free String */

#define FSTITLE          11  /* Free String */

#define MENUST           12  /* Free String */

#define TASKSW           13  /* Free String */

#define TOSLEEP          14  /* Free String */

#define ASCIIT           15  /* Free String */

#define REDRAW           16  /* Free String */

#define S0               17  /* Free String */

#define S1               18  /* Free String */

#define S2               19  /* Free String */

#define S3               20  /* Free String */

#define S4               21  /* Free String */

#define S5               22  /* Free String */

#define S6               23  /* Free String */

#define S7               24  /* Free String */

#define S8               25  /* Free String */

#define S9               26  /* Free String */

#define S10              27  /* Free String */

#define S11              28  /* Free String */

#define S12              29  /* Free String */

#define S13              30  /* Free String */

#define S14              31  /* Free String */

#define S15              32  /* Free String */

#define S16              33  /* Free String */

#define NEW              34  /* Free String */

#define FLK0             35  /* Free String */

#define FLK1             36  /* Free String */

#define FLK2             37  /* Free String */

#define FLK3             38  /* Free String */

#define SSYSTEM          39  /* Free String */

#define SUNKNOWN         40  /* Free String */

#define SUNDEF           41  /* Free String */

#define HELPMAIN         42  /* Free String */

#define DOUBLE           43  /* Free String */

#define INTRLACE         44  /* Free String */

#define FTMPSTR          45  /* Free String */

#define FPERSTR          46  /* Free String */

#define WGDINFO          47  /* Free String */

#define WGDMENU          48  /* Free String */

#define FOSELSTR         49  /* Free String */
