/* Resource file indices for FSEL. */

#define FSEL             0   /* Form/Dialog-box */
#define FSTITLE          1   /* BOXTEXT in tree FSEL */
#define FSPTHB           2   /* BOXTEXT in tree FSEL */
#define FSPLEFT          3   /* BOXCHAR in tree FSEL */
#define FSPATH           4   /* FBOXTEXT in tree FSEL */
#define FSPRIGHT         5   /* BOXCHAR in tree FSEL */
#define FS1COL           6   /* BOXTEXT in tree FSEL */
#define FSUPDATE         7   /* BOXTEXT in tree FSEL */
#define FSSORT           8   /* BOXTEXT in tree FSEL */
#define FSTOOLS          9   /* BOXTEXT in tree FSEL */
#define FSFEXT           10  /* BOXTEXT in tree FSEL */
#define FSDA             13  /* BOXCHAR in tree FSEL */
#define FSDDOWN          22  /* BOXCHAR in tree FSEL */
#define FSDUP            23  /* BOXCHAR in tree FSEL */
#define FSOOUTER         24  /* BOX in tree FSEL */
#define FSCLOSE          25  /* BOXCHAR in tree FSEL */
#define FSROOT           26  /* BOXCHAR in tree FSEL */
#define FSALL1           27  /* BOXTEXT in tree FSEL */
#define FSONSDT          28  /* BOXCHAR in tree FSEL */
#define FSFFOLD1         30  /* TEXT in tree FSEL */
#define FSOUP            40  /* BOXCHAR in tree FSEL */
#define FSOBIG           41  /* BOX in tree FSEL */
#define FSOSMALL         42  /* BOX in tree FSEL */
#define FSODOWN          43  /* BOXCHAR in tree FSEL */
#define FSFOUTER         44  /* BOX in tree FSEL */
#define FSFILE           45  /* FBOXTEXT in tree FSEL */
#define FSFNSDT          46  /* BOXCHAR in tree FSEL */
#define FSFFILE1         48  /* TEXT in tree FSEL */
#define FSFUP            58  /* BOXCHAR in tree FSEL */
#define FSFBIG           59  /* BOX in tree FSEL */
#define FSFSMALL         60  /* BOX in tree FSEL */
#define FSFDOWN          61  /* BOXCHAR in tree FSEL */
#define FSFOUTER2        62  /* BOX in tree FSEL */
#define FSCLOSE2         63  /* BOXCHAR in tree FSEL */
#define FSROOT2          64  /* BOXCHAR in tree FSEL */
#define FSNAME2          65  /* FBOXTEXT in tree FSEL */
#define FSALL2           66  /* BOXTEXT in tree FSEL */
#define FSFFILE2         68  /* TEXT in tree FSEL */
#define FSFUP2           78  /* BOXCHAR in tree FSEL */
#define FSFBIG2          79  /* BOX in tree FSEL */
#define FSFSMALL2        80  /* BOX in tree FSEL */
#define FSFDOWN2         81  /* BOXCHAR in tree FSEL */
#define FSHELP           82  /* BOXTEXT in tree FSEL */
#define FSOK             83  /* BUTTON in tree FSEL */
#define FSCANCEL         84  /* BUTTON in tree FSEL */
#define FSITEMS          85  /* BOXTEXT in tree FSEL */
#define FSBYTES          86  /* BOXTEXT in tree FSEL */

#define FFOLD            1   /* Form/Dialog-box */
#define FFNAME           2   /* FTEXT in tree FFOLD */
#define FFOK             3   /* BUTTON in tree FFOLD */
#define FFCANCEL         4   /* BUTTON in tree FFOLD */

#define FINFO            2   /* Form/Dialog-box */
#define FSROLD           2   /* FTEXT in tree FINFO */
#define FSRSIZEO         3   /* TEXT in tree FINFO */
#define FSRSIZE          4   /* BOXTEXT in tree FINFO */
#define FSRDATEO         5   /* TEXT in tree FINFO */
#define FSRDATE          6   /* STRING in tree FINFO */
#define FSRFOLDMSG       7   /* IBOX in tree FINFO */
#define FSRFOLDO         8   /* TEXT in tree FINFO */
#define FSRFOLD          9   /* BOXTEXT in tree FINFO */
#define FSRFILEO         10  /* TEXT in tree FINFO */
#define FSRFILES         11  /* BOXTEXT in tree FINFO */
#define FSRRO            12  /* BUTTON in tree FINFO */
#define FSROK            13  /* BUTTON in tree FINFO */
#define FSRSKIP          14  /* BUTTON in tree FINFO */
#define FSRCANCEL        15  /* BUTTON in tree FINFO */
#define FSRDELMSG        16  /* IBOX in tree FINFO */
#define FSRMSG1          17  /* TEXT in tree FINFO */
#define FSRMSG2          18  /* TEXT in tree FINFO */

#define PATHLIST         3   /* Form/Dialog-box */
#define PATH1            12  /* STRING in tree PATHLIST */

#define EXTLIST          4   /* Form/Dialog-box */

#define FSHELPTXT        5   /* Form/Dialog-box */

#define OPLIST           6   /* Form/Dialog-box */
#define OPINFO           1   /* STRING in tree OPLIST */
#define OPFIND           2   /* STRING in tree OPLIST */
#define OPCOPY           4   /* STRING in tree OPLIST */
#define OPMOVE           5   /* STRING in tree OPLIST */
#define OPDEL            6   /* STRING in tree OPLIST */
#define OPFOLD           8   /* STRING in tree OPLIST */
#define OPFREE           9   /* STRING in tree OPLIST */

#define SORTLIST         7   /* Form/Dialog-box */
#define SORTNAME         1   /* STRING in tree SORTLIST */

#define FFIND            8   /* Form/Dialog-box */
#define FFINAME          2   /* FTEXT in tree FFIND */
#define FFIHID           4   /* IBOX in tree FFIND */
#define FFIFOO           5   /* TEXT in tree FFIND */
#define FFIFOLD          6   /* BOXTEXT in tree FFIND */
#define FFIFOF           7   /* TEXT in tree FFIND */
#define FFIFILE          8   /* BOXTEXT in tree FFIND */
#define FFISHOW          9   /* BUTTON in tree FFIND */
#define FFINEXT          10  /* BUTTON in tree FFIND */

#define FCOPY            9   /* Form/Dialog-box */
#define FCOPTITL         1   /* STRING in tree FCOPY */
#define FCOPFOLDO        2   /* TEXT in tree FCOPY */
#define FCOPFOLD         3   /* BOXTEXT in tree FCOPY */
#define FCOPFILEO        4   /* TEXT in tree FCOPY */
#define FCOPFILE         5   /* BOXTEXT in tree FCOPY */
#define FCOPHID2         6   /* BUTTON in tree FCOPY */
#define FCOPNAME         7   /* FTEXT in tree FCOPY */
#define FCOPSKIP         9   /* BUTTON in tree FCOPY */
#define FCOPCOP          10  /* BUTTON in tree FCOPY */
#define FCOPHID1         11  /* IBOX in tree FCOPY */
#define FCOPFOO          12  /* TEXT in tree FCOPY */
#define FCOPFOGO         13  /* BOXTEXT in tree FCOPY */
#define FCOPFIO          14  /* TEXT in tree FCOPY */
#define FCOPFIGO         15  /* BOXTEXT in tree FCOPY */
